/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import genetics.Solution;
import javax.swing.JOptionPane;

/**
 *
 * @author nikol
 */
public class Home extends javax.swing.JFrame
{
    /**
     * Creates new form Home
     */
    public Home()
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txtSum = new javax.swing.JTextField();
        btnSolve = new javax.swing.JButton();
        btnGreedy = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtFinalSum = new javax.swing.JTextField();
        txtSolution = new javax.swing.JTextField();
        txtNoIter = new javax.swing.JTextField();
        txtExeTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sum");

        txtSum.setText("0");

        btnSolve.setText("Solve");
        btnSolve.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSolveActionPerformed(evt);
            }
        });

        btnGreedy.setText("Greedy");
        btnGreedy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGreedyActionPerformed(evt);
            }
        });

        jLabel2.setText("Final sum");

        txtFinalSum.setEditable(false);

        txtSolution.setEditable(false);
        txtSolution.setText("1 2 3 4 5 6 7 8 9 10");

        txtNoIter.setEditable(false);

        txtExeTime.setEditable(false);

        jLabel3.setText("Solution");

        jLabel4.setText("No. of iterations");

        jLabel5.setText("Execution time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSolve)
                        .addGap(14, 14, 14)
                        .addComponent(btnGreedy))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFinalSum)
                            .addComponent(txtNoIter)
                            .addComponent(txtExeTime)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(58, 58, 58)
                            .addComponent(txtSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolve)
                    .addComponent(btnGreedy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFinalSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExeTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**Wrapper for input validation**/
    private boolean inputIsInvalid(String input)
    {
        int number=0;
        /**Are we able to parse**/
        try
        { 
        number=Integer.parseInt(input); 
        }
        catch(NumberFormatException e)
        { 
            return true; 
        }
        catch(NullPointerException e)
        {
            return true;
        }
        /**Are the numbers in range**/
        if(number<20 || number>90)return true;
        return false;
    }
    public void alert(String message)
    {
        /**Show some message**/
        JOptionPane.showMessageDialog(
                this,
                message,
                "Alert.",
                JOptionPane.PLAIN_MESSAGE
        );
    }
    /**Filling in text fields in the form**/
    private void fillTheForm(String solution)
    {
        //alert(solution);
        String[] separatedSolution=solution.split("===");
        txtFinalSum.setText(separatedSolution[0]);
        //txtSolution.setText(separatedSolution[1]);
        txtNoIter.setText(separatedSolution[2]);
        txtExeTime.setText(separatedSolution[3]+" miliseconds");
        
        /**Putting coins back to buckets**/
        String finalSolution=Solution.putCoinsToBuckets(separatedSolution[1]);
        txtSolution.setText(finalSolution);
    }
    

    private void btnSolveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSolveActionPerformed
    {//GEN-HEADEREND:event_btnSolveActionPerformed
        if (inputIsInvalid(txtSum.getText()))
        {
            alert("Error inputting text.");
            return;
        }
        String solution = genetics.Solution.solve(Integer.parseInt(txtSum.getText())/*,this*/);
        fillTheForm(solution);
    }//GEN-LAST:event_btnSolveActionPerformed

    private void btnGreedyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGreedyActionPerformed
    {//GEN-HEADEREND:event_btnGreedyActionPerformed
        if (inputIsInvalid(txtSum.getText()))
        {
            alert("Error inputting text.");
            return;
        }
        String solution = genetics.Solution.solveGreedy(Integer.parseInt(txtSum.getText())/*,this*/);
        fillTheForm(solution);
    }//GEN-LAST:event_btnGreedyActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGreedy;
    private javax.swing.JButton btnSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtExeTime;
    private javax.swing.JTextField txtFinalSum;
    private javax.swing.JTextField txtNoIter;
    private javax.swing.JTextField txtSolution;
    private javax.swing.JTextField txtSum;
    // End of variables declaration//GEN-END:variables
}
